controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Controllers for the arm and hand
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    revo2_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# RM65 Arm Configuration
rm_group_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      joint1:
        trajectory: 0.05
        goal: 0.03
      joint2:
        trajectory: 0.05
        goal: 0.03
      joint3:
        trajectory: 0.05
        goal: 0.03
      joint4:
        trajectory: 0.05
        goal: 0.03
      joint5:
        trajectory: 0.05
        goal: 0.03
      joint6:
        trajectory: 0.05
        goal: 0.03

# revo2 Hand Configuration 
revo2_hand_controller:
  ros__parameters:
    joints:
      - right_thumb_metacarpal_joint
      - right_thumb_proximal_joint
      - right_index_proximal_joint
      - right_middle_proximal_joint
      - right_ring_proximal_joint
      - right_pinky_proximal_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    # constraints:
    #   stopped_velocity_tolerance: 0.01
    #   goal_time: 1.0
    #   right_thumb_metacarpal_joint:
    #     trajectory: 0.05
    #     goal: 0.03
    #   right_thumb_proximal_joint:
    #     trajectory: 0.05
    #     goal: 0.03
    #   right_index_proximal_joint:
    #     trajectory: 0.05
    #     goal: 0.03
    #   right_middle_proximal_joint:
    #     trajectory: 0.05
    #     goal: 0.03
    #   right_ring_proximal_joint:
    #     trajectory: 0.05
    #     goal: 0.03
    #   right_pinky_proximal_joint:
    #     trajectory: 0.05
    #     goal: 0.03
