controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_revo2_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_revo2_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Left Hand Configuration
left_revo2_hand_controller:
  ros__parameters:
    joints:
      - left_thumb_metacarpal_joint
      - left_thumb_proximal_joint
      - left_index_proximal_joint
      - left_middle_proximal_joint
      - left_ring_proximal_joint
      - left_pinky_proximal_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

# Right Hand Configuration
right_revo2_hand_controller:
  ros__parameters:
    joints:
      - right_thumb_metacarpal_joint
      - right_thumb_proximal_joint
      - right_index_proximal_joint
      - right_middle_proximal_joint
      - right_ring_proximal_joint
      - right_pinky_proximal_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
